package com.example.liveplayerstats

enum class TeamImgResources(val id: Int) {
    ATL(R.drawable.ic_hawks),
    BOs(R.drawable.ic_celtics),
    BKN(R.drawable.ic_nets),
    CHA(R.drawable.ic_hornets),
    CHI(R.drawable.ic_bulls),
    CLE(R.drawable.ic_cavaliers),
    DAL(R.drawable.ic_mavericks),
    DEN(R.drawable.ic_nuggets),
    DET(R.drawable.ic_pistons),
    GSW(R.drawable.ic_warriors),
    HOU(R.drawable.ic_rockets),
    IND(R.drawable.ic_pacers),
    LAC(R.drawable.ic_clippers),
    LAL(R.drawable.ic_lakers),
    MEM(R.drawable.ic_grizzlies),
    MIA(R.drawable.ic_heat),
    MIL(R.drawable.ic_bucks),
    MIN(R.drawable.ic_timberwolves),
    NOP(R.drawable.ic_pelicans),
    NYK(R.drawable.ic_knicks),
    OKC(R.drawable.ic_thunder),
    ORL(R.drawable.ic_magic),
    PHI(R.drawable.ic_76ers),
    PHX(R.drawable.ic_suns),
    POR(R.drawable.ic_blazers),
    SAC(R.drawable.ic_kings),
    SAS(R.drawable.ic_spurs),
    TOR(R.drawable.ic_raptors),
    UTA(R.drawable.ic_jazz),
    WAS(R.drawable.ic_wizards)
}