package com.example.liveplayerstats.boxscore

data class ActivePlayer(
    val assists: String,
    val blocks: String,
    val defReb: String,
    val dnp: String,
    val fga: String,
    val fgm: String,
    val fgp: String,
    val firstName: String,
    val fta: String,
    val ftm: String,
    val ftp: String,
    val isOnCourt: Boolean,
    val jersey: String,
    val lastName: String,
    val min: String,
    val offReb: String,
    val pFouls: String,
    val personId: String,
    val player_code: String,
    val plusMinus: String,
    val points: String,
    val pos: String,
    val position_full: String,
    val steals: String,
    val teamId: String,
    val totReb: String,
    val tpa: String,
    val tpm: String,
    val tpp: String,
    val turnovers: String
)